#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Original 
#bspc monitor -d I II III IV V VI VII VIII IX X

# Multiple Monitor Configuration 
if [[ $HOSTNAME == arch-lt ]]; then
	bspc monitor LVDS-2 -d I II III IV V VI VII VIII IX X
elif [[ $HOSTNAME == arch-dt ]]; then
	bspc monitor HDMI-2 -d I II III IV V
	bspc monitor DP-2 -d VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

# Default rules--not deleting so I have an example 

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Set Pycharm to floating 
bspc rule -a jetbrains-pycharm-ce state=floating

# Set cursor 
xsetroot -cursor_name left_ptr
 
# Launch programs at start 
sh $HOME/.config/bspwm/launch.sh & 

# Fix Java display issues
wmname LG3D

# Change boarder color 
bspc config active_border_color \#cda8f9
bspc config normal_border_color \#8cb5fb
bspc config focused_border_color \#95e3d6
