#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Original 
#bspc monitor -d I II III IV V VI VII VIII IX X

# Big and Small Monitor Configuration w/ Laptop option 
# if [[ $HOSTNAME == arch-dt ]]; then
# 	bspc monitor HDMI-2 -d I II III IV V
# 	bspc monitor DP-2 -d VI VII VIII IX X
# elif [[ $HOSTNAME == arch-lt ]]; then
# 	bspc monitor LVDS-2 -d I II III IV V VI VII VIII IX X

# fi

# Big Monitor and Big Goodwill Monitor Configuration 

# Roman Numeral Setup
# if [[ $HOSTNAME == arch-dt ]]; then
# 	bspc monitor HDMI-2 -d I ii iii IV V vi vii 
# 	bspc monitor DP-2 -d I ii iii X
# fi

# labled desktops
if [[ $HOSTNAME == arch-dt ]]; then
	bspc monitor HDMI-2 -d General Terminal Code Script Media  
	bspc monitor DP-2 -d X XX XXX
fi

bspc config border_width         2 
bspc config window_gap          27 # originally 12

# original - 0.52
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

# Default rules--not deleting so I have an example 

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Set Pycharm to floating 
bspc rule -a jetbrains-pycharm-ce state=floating

# Set qjoypad to floating
bspc rule -a qjoypad state=floating

# Set Spotify to desktop 7
bspc rule -a Spotify desktop='^7'

# Set cursor 
xsetroot -cursor_name left_ptr
 
# Launch programs at start 
sh $HOME/.config/bspwm/launch.sh & 

# Fix Java display issues
wmname LG3D 

# Change boarder color 
# unselected secondary monitor
bspc config active_border_color \#3b4b66 # red
# unselected
bspc config normal_border_color \#4e3c7c # green
# selected boarder
bspc config focused_border_color \#e1a58b #yellow

# Launch polybar at start 
$HOME/.config/polybar/launch.sh
