#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Original 
#bspc monitor -d I II III IV V VI VII VIII IX X

# Multiple Monitor Configuration 
if [[ $HOSTNAME == arch ]]; then
	bspc monitor LVDS-2 -d I II III IV V VI VII VIII IX X
elif [[ $HOSTNAME == arch-dt ]]; then
	bspc monitor HDMI-2 -d I II III IV V
	bspc monitor DP-2 -d VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#!/bin/bash 



